name: Hexo CI

on:
  push:
    branches:
      - source

env:
  GIT_USER: Gadfly
  GIT_EMAIL: gadfly@gadfly.vip
  DEPLOY_REPO: gadfly3173/gadfly3173.github.io
  DEPLOY_BRANCH: master
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build on node ${{ matrix.node-version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [22.x]

    steps:
      - name: Setup Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HEXO_DEPLOY_PRI }}
          known_hosts: 'github.com'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout deploy repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.DEPLOY_REPO }}
          ref: ${{ env.DEPLOY_BRANCH }}
          path: .deploy_git

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: |
          yarn

      - name: Update post update time
        run: |
          yarn post-update-time

      - name: Deploy hexo
        run: |
          yarn release
